Update projet.py
Alexiscomete/NSI-projet-compression pull request #13
Opened 2023-04-05 09:09 UTC by NEPETAISCUTE

j'ai corrigé tous les bugs causés par soucis de conversion binaire-décimal et inversement, l'entiereté du programme est fonctionnel, testé avec un texte lorem ipsum de 500 mots.

2023-04-05 09:15 UTC, NEPETAISCUTE commented
j'aimerais spécifier, la taille du fichier d'origine étais de 3,3Ko, contre 1,7Ko pour la version compressée

2023-04-05 11:18 UTC, Alexiscomete requested changes
Presque parfait

2023-04-05 11:18 UTC, Alexiscomete commented on projet.py
> +    fichier_sortie = input("Quel est le nom du fichier compressé/décompressé?: ")
```suggestion
    ENCODER_FICHIER = 1
    DECODER_FICHIER = 2
    enco_deco = ENCODER_FICHIER + DECODER_FICHIER
    while not (enco_deco in [ENCODER_FICHIER, DECODER_FICHIER]):
        print(ENCODER_FICHIER, ": encoder")
        print(DECODER_FICHIER, ": decoder")
        enco_deco = int(input("Faites votre choix : "))

    fichier_chemin = input("Quel fichier voulez-vous coder ou décoder ?: ")
    fichier_sortie = input("Quel est le nom du fichier compressé/décompressé ?: ")
```

2023-04-05 11:18 UTC, Alexiscomete commented on projet.py
> +    fichier_sortie = input("Quel est le nom du fichier compressé/décompressé?: ")
Sinon très bons changements

2023-04-05 11:18 UTC, Alexiscomete commented on projet.py
> +def int_to_bin_padding(n, size):
Bien. Pourquoi ne pas faire une seule fonction ?

2023-04-05 11:18 UTC, Alexiscomete commented on projet.py
> +            data += int_to_bin_padding(int.from_bytes(fichier.read(1), "little"),8)
❤ beaucoup plus lisible

2023-04-05 11:28 UTC, Alexiscomete commented
Description modifiée

2023-04-05 12:12 UTC, NEPETAISCUTE commented on projet.py
> +            binstring += s[i*8+j]
ça reviens à découper en strings de 8 caractère le string originel s

2023-04-05 12:13 UTC, NEPETAISCUTE commented on projet.py
> +        bytearr.append(bin_to_int(binstring))
ça fais la même chose que pour l'autre boucle binstring, sauf que pour celle là, dans le cas ou on arrive à la fin, on ajoute des 0 de padding pour tout faire tenir dans un octet

2023-04-05 12:14 UTC, NEPETAISCUTE commented on projet.py
> +            data += int_to_bin_padding(int.from_bytes(fichier.read(1), "little"),8)
content de l'apprendre!!!

2023-04-05 14:41 UTC, Alexiscomete commented on projet.py
> +            binstring += s[i*8+j]
Mais pourquoi faire ça en sachant que je string de base n'est jamais modifié et binstring jamais utilisé ?

2023-04-05 14:43 UTC, Alexiscomete commented on projet.py
> +def int_to_bin_padding(n, size):
Ok je vois. Mais si tu met une valeur pas défaut pas besoin.

2023-04-06 13:07 UTC, Alexiscomete commented
@NEPETAISCUTE je me suis permis de modifier dans 1bff6e4 certains éléments

2023-04-06 13:08 UTC, Alexiscomete commented
Pour moi on peut merge

2023-04-06 13:24 UTC, merged