Update projet.py
Alexiscomete/NSI-projet-compression pull request #8
Opened 2023-04-01 13:19 UTC by Nekokimi0

2023-04-01 13:35 UTC, heavnscloud approved these changes

2023-04-01 13:40 UTC, Alexiscomete requested changes
Petite proposition, sinon le programme semble très bien et optimisé

2023-04-01 13:40 UTC, Alexiscomete commented on projet.py
> +                num = ''
```suggestion
    for c in texte:
        num += c
        for item in tab.items(): # .items() récupère une liste de tuples (cle, valeur)
            if num == item[1]:
                txt += item[0]
                num = ''
```

2023-04-01 13:40 UTC, Alexiscomete commented on projet.py
> +                num = ''
@heavnscloud @Nekokimi0 vous en pensez quoi ?

2023-04-03 11:37 UTC, Alexiscomete commented on projet.py
> +                num = ''
N'ayant pas de réponse je commit

2023-04-03 11:38 UTC, merged