Update projet.py
Alexiscomete/NSI-projet-compression pull request #9
Opened 2023-04-01 20:48 UTC by NEPETAISCUTE

ajout de la fonction pour charger les données compressées depuis un fichier

2023-04-02 08:26 UTC, Alexiscomete commented
Il faudrait résoudre les conflits. Tu as le bouton ou je le fais ?

2023-04-02 08:31 UTC, NEPETAISCUTE commented
c'est bon, les conflits sont résolus

2023-04-02 08:31 UTC, Alexiscomete commented
Cool, je regarde ça

2023-04-02 08:37 UTC, Alexiscomete requested changes
Le code semble très bien, je n'aurais pas fais comme ça étant donné que je n'ai pas beaucoup de connaissances dans la sauvegarde de fichiers. Juste 2-3 points à éclaircir sinon le passage à l'oral risque d'être difficile. (Oui je n'approuve jamais du premier coup 😅)

2023-04-02 08:37 UTC, Alexiscomete commented on projet.py
> +    bink = {} #ce sera notre table
pourquoi bink et pas table_retour ?

2023-04-02 08:37 UTC, Alexiscomete commented on projet.py
> +            return None #il faudra détecter que la fonction ne retourne pas None.
Pourquoi ne pas retourner une erreur ? Après c'est un choix compréhensible.

2023-04-02 08:37 UTC, Alexiscomete commented on projet.py
> +            tmpk = inttobin(int.from_bytes(f.read(1), "little") & 2**bitlen-1) #le & ici représente un opérateur "et" logique, cela sert à construire un masque de bits, pour récupérer seulement la pa
Que signifie tmpk ?

2023-04-02 08:38 UTC, NEPETAISCUTE commented on projet.py
> +            return None #il faudra détecter que la fonction ne retourne pas None.
juste une habitude que j'ai gardée du C, si tu veux tu peux retourner une erreur à la place

2023-04-02 08:39 UTC, NEPETAISCUTE commented on projet.py
> +    bink = {} #ce sera notre table
y'a pas de soucis à l'appeler table_retour, je l'avais juste nommée comme dans la fonction de sauvegarde

2023-04-02 08:39 UTC, NEPETAISCUTE commented on projet.py
> +            tmpk = inttobin(int.from_bytes(f.read(1), "little") & 2**bitlen-1) #le & ici représente un opérateur "et" logique, cela sert à construire un masque de bits, pour récupérer seulement la pa
temporary key, ou clé temporaire si tu préfère

2023-04-02 08:40 UTC, Alexiscomete commented on projet.py
> +            tmpk = inttobin(int.from_bytes(f.read(1), "little") & 2**bitlen-1) #le & ici représente un opérateur "et" logique, cela sert à construire un masque de bits, pour récupérer seulement la pa
Franchement, ce n'est pas compréhensible du premier coup

2023-04-02 08:41 UTC, NEPETAISCUTE commented on projet.py
> +            tmpk = inttobin(int.from_bytes(f.read(1), "little") & 2**bitlen-1) #le & ici représente un opérateur "et" logique, cela sert à construire un masque de bits, pour récupérer seulement la pa
je comprends, y'a pas de soucis, j'avais pas de meilleur nom sur le moment, j'avais fait ça vers 23h et j'étais pas au plus haut de ma forme

2023-04-02 08:44 UTC, Alexiscomete commented on projet.py
> +            tmpk = inttobin(int.from_bytes(f.read(1), "little") & 2**bitlen-1) #le & ici représente un opérateur "et" logique, cela sert à construire un masque de bits, pour récupérer seulement la pa
Ah ! Ok

2023-04-03 12:04 UTC, Alexiscomete requested changes
Propositions

2023-04-03 12:04 UTC, Alexiscomete commented on projet.py
> +    return bink,data
```suggestion
    table_retour = {} #ce sera notre table

    with open(path, "rb") as fichier:
        # read permet de lire n octet.s
        if fichier.read(3)!=b"HCS": #verifier que le fichier soit bien à notre format
            print("Le fichier n'est pas au format HCS")
            return None #il faudra détecter que la fonction ne retourne pas None.
        taille_cle = int.from_bytes(f.read(4),"little") 
        taille_donnes = int.from_bytes(f.read(4),"little") 

        for _ in range(taille_cle//3): #boucle pour récupérer notre table, et en faire un dictionnaire
            taille_cle_lettre = int.from_bytes(fichier.read(1), "little")
            cle_lettre = int_to_bin(int.from_bytes(fichier.read(1), "little") & 2**taille_cle_lettre-1) #le & ici représente un opérateur "et" logique, cela sert à construire un masque de bits, pour récupérer seulement la partie qui nous intéresse dans l'octet.
            table_retour[cle_lettre] = fichier.read(1).decode("ascii")
        data = int_to_bin(int.from_bytes(fichier.read(taille_donnees//8+1), "little") & 2**taille_donnees-1) 
    return table_retour,data
```

2023-04-03 15:37 UTC, NEPETAISCUTE commented on projet.py
> +            return None #il faudra détecter que la fonction ne retourne pas None.
bah avec l'exception, ça fermera le programme de force, avec None, on a moyen de redemander le fichier à l'utilisateur

2023-04-03 16:09 UTC, Alexiscomete commented on projet.py
> +            return None #il faudra détecter que la fonction ne retourne pas None.
L'exception peut-être catch

2023-04-03 16:10 UTC, Alexiscomete commented on projet.py
> +            return None #il faudra détecter que la fonction ne retourne pas None.
Au pire on s'en occupe mercredi

2023-04-03 16:11 UTC, Alexiscomete approved these changes

2023-04-03 16:11 UTC, merged